### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by osimar** [zohmg/zohmg#41]
Hi. I've been trying to run command zohmg setup, but always end up on this error below. I somewhat believe this is a python error, tough I can't figure out how to correct it. Can anyone gimme a hand ?

Thanks.

[root@virid-tasks television]# zohmg setup
creating table 'television'
Traceback (most recent call last):
  File "/usr/bin/zohmg", line 7, in ?
    sys.exit(
  File "/usr/lib64/python2.4/cmd.py", line 68, in zohmg
    identchars = IDENTCHARS
  File "/usr/lib64/python2.4/cmd.py", line 90, in setup
    import sys
  File "build/bdist.linux-x86_64/egg/zohmg/setup.py", line 36, in go
  File "build/bdist.linux-x86_64/egg/zohmg/utils.py", line 50, in create_or_bust
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 835, in createTable
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 843, in send_createTable
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 3500, in write
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/ttypes.py", line 206, in write
  File "/usr/local/lib/zohmg/egg/Thrift-0.1-py2.5-linux-i686.egg/thrift/protocol/TBinaryProtocol.py", line 123, in writeString
  File "/usr/local/lib/zohmg/egg/Thrift-0.1-py2.5-linux-i686.egg/thrift/transport/TTransport.py", line 159, in write
TypeError: write() argument 1 must be string or read-only character buffer, not dict

**Comment by fredrik** [comment]
I think you might be right about it being a Python error. It seems you are using Python 2.4. Could you try using Python 2.5 and see if the error persists?

**Comment by osimar** [comment]
Hi, fredrikmollerstrand. I updated python to 2.5 version, but got this new error below. However, this time I think it's another kind of error, a zohmg error. Can someone enlighten me on this, please ?

Traceback (most recent call last):
  File "/usr/bin/zohmg", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

**Comment by fredrik** [comment]
Osimar, pkg_resources is part of setuptools. You need to have setuptools installed for Python 2.5 (you might already have it installed for Python 2.4, but that will not work). Hope that will get you going!

**Comment by osimar** [comment]
Very sorry, fredrikmollerstrand, am very thankful you've been so helpful, but i ran into another error. I've installed setuptools setuptools-0.6c11-py2.5.egg:

[root@virid-tasks site-packages]# easy_install setuptools-0.6c11-py2.5.egg
Processing setuptools-0.6c11-py2.5.egg
setuptools 0.6c11 is already the active version in easy-install.pth
Installing easy_install script to /usr/local/bin
Installing easy_install-2.5 script to /usr/local/bin
Installed /usr/local/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg
Processing dependencies for setuptools==0.6c11
Finished processing dependencies for setuptools==0.6c11

Then, I ran [root@virid-tasks television]# zohmg setup
And I got this:

Traceback (most recent call last):
  File "/usr/bin/zohmg", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py", line 2603, in <module>
  File "/usr/local/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py", line 666, in require
  File "/usr/local/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: zohmg==0.2.1

I've checked and file /usr/local/lib/python2.5/site-packages/setuptools-0.6c11-py2.5.egg/pkg_resources.py does not exist.

The only file with that name exists here: /usr/lib/python2.4/site-packages/pkg_resources.py

Then I copied it to /usr/local/lib/python2.5/site-packages/ and ran zohmg setup again.
That got me:

Traceback (most recent call last):
  File "/usr/bin/zohmg", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.5/site-packages/pkg_resources.py", line 2603, in <module>

  File "/usr/local/lib/python2.5/site-packages/pkg_resources.py", line 666, in require
    search_path = sys.path
  File "/usr/local/lib/python2.5/site-packages/pkg_resources.py", line 565, in resolve

pkg_resources.DistributionNotFound: zohmg==0.2.1

Am very sorry, but it seems i've ran to a dead end street. :) 
Have no idea.

I trying to use zohmg.

I've already installed Hadoop and Hbase.

**Comment by fredrik** [comment]
No problem, osimar! I think what happened here was that you installed Zohmg back when you only had Python 2.4 installed on your system. That would explain why /usr/local/lib/python2.5/site-packages/pkg_resources.py can not find the Zohmg distribution (i.e. the egg). Try reinstalling Zohmg with Python 2.5 by running the command 'sudo python2.5 install.py' (or similar) from the Zohmg installation directory.

**Comment by osimar** [comment]
Hi, fredrikmollerstrand, here I come again... :)

I reinstalled Zohmg, did everything from the beggining, with Python 2.5, and yet, I fell on the same error as before. Dude, either I am very stupid or Zohmg is very hard. :)

[root@virid-tasks television]# zohmg setup
creating table 'television'
Traceback (most recent call last):
  File "/usr/bin/zohmg", line 8, in <module>
    load_entry_point('zohmg==0.2.1', 'console_scripts', 'zohmg')()
  File "/usr/local/lib/python2.5/cmd.py", line 68, in zohmg
    identchars = IDENTCHARS
  File "/usr/local/lib/python2.5/cmd.py", line 90, in setup
    import sys
  File "build/bdist.linux-x86_64/egg/zohmg/setup.py", line 36, in go
  File "build/bdist.linux-x86_64/egg/zohmg/utils.py", line 50, in create_or_bust
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 835, in createTable
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 843, in send_createTable
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 3500, in write
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/ttypes.py", line 206, in write
  File "/usr/local/lib/zohmg/egg/Thrift-0.1-py2.5-linux-i686.egg/thrift/protocol/TBinaryProtocol.py", line 123, in writeString
  File "/usr/local/lib/zohmg/egg/Thrift-0.1-py2.5-linux-i686.egg/thrift/transport/TTransport.py", line 159, in write
TypeError: write() argument 1 must be string or read-only character buffer, not dict

**Comment by fredrik** [comment]
Oh my, back to where we started indeed! :-)

What version of HBase are you using?

**Comment by osimar** [comment]
:)
Hbase is at version 0.20.5

I did a jps, check the result:

[root@virid-tasks bin]# jps
13696 QuorumPeerMain
28932 SecondaryNameNode
6992 ThriftServer
29283 HMaster
28790 DataNode
28670 NameNode
18968 Jps

I guess that means Hadoop are HBase are running, right ?

**Comment by fredrik** [comment]
The issue here is likely that HBase's Thrift interface changed since 0.20. I'll recreate the error locally and provide a fix.

(They seem to be running, yes.)

**Comment by osimar** [comment]
Hum...

In the meanwhile, should I use a 0.20 HBases version to give it a try ?

What do you think ?

**Comment by fredrik** [comment]
Yeah, that's a good idea!

**Comment by osimar** [comment]
Hi, fredrikmollerstrand, dunno if it's any of help to you, but check this out:

# /usr/lib/hbase-0.20.5/bin/hbase shell

HBase Shell; enter 'help<RETURN>' for list of supported commands.
Version: 0.20.5, r956266, Sat Jun 19 12:25:12 PDT 2010
hbase(main):001:0> status
NativeException: org.apache.hadoop.hbase.MasterNotRunningException: null

# jps

31150 Jps
13696 QuorumPeerMain
28932 SecondaryNameNode
6992 ThriftServer
28790 DataNode
28670 NameNode
27712 Main

Do you know if this could be the cause of the zohmg errors ?

**Comment by fredrik** [comment]
Oh yes, you should have HMaster in that jps output. (You did earlier.)

**Comment by osimar** [comment]
Hi, here I come. :)

Ok, so I've uninstalled everything and used the /usr/lib/zohmg-zohmg-b059a62/scripts/install_hadoop_hbase.sh script.

I've altered versions and tar.gz's download addresses and both hadoop and hbase were successful installed and built.

Then I started hadoop and hbase and all was OK until then.

Now, when I run zohmg setup, it returns this:

creating table 'television'
could not setup thrift transport.
is the thrift server turned on?

Then i start the thrift server with [root@virid-tasks bin]# ./hbase thrift start

Then all hell breaks loose...:)

It returns this:

10/07/07 11:06:15 INFO ThriftServer: starting HBase Thrift server on port 9090
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:zookeeper.version=3.2.2-888565, built on 12/08/2009 21:51 GMT
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:host.name=uolhostidc4060
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:java.version=1.6.0_20
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:java.vendor=Sun Microsystems Inc.
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:java.home=/usr/java/jdk1.6.0_20/jre
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:java.class.path=/opt/hbase-0.20.5/bin/../conf:/usr/java/jdk1.6.0_20//lib/tools.jar:/opt/hbase-0.20.5/bin/../build/classes:/opt/hbase-0.20.5/bin/../build/test:/opt/hbase-0.20.5/bin/../build:/opt/hbase-0.20.5/bin/..:/opt/hbase-0.20.5/bin/../hbase-0.20.5.jar:/opt/hbase-0.20.5/bin/../hbase-0.20.5-test.jar:/opt/hbase-0.20.5/bin/../lib/commons-cli-2.0-SNAPSHOT.jar:/opt/hbase-0.20.5/bin/../lib/commons-el-from-jetty-5.1.4.jar:/opt/hbase-0.20.5/bin/../lib/commons-httpclient-3.0.1.jar:/opt/hbase-0.20.5/bin/../lib/commons-logging-1.0.4.jar:/opt/hbase-0.20.5/bin/../lib/commons-logging-api-1.0.4.jar:/opt/hbase-0.20.5/bin/../lib/commons-math-1.1.jar:/opt/hbase-0.20.5/bin/../lib/hadoop-0.20.2-core.jar:/opt/hbase-0.20.5/bin/../lib/hadoop-0.20.2-test.jar:/opt/hbase-0.20.5/bin/../lib/jasper-compiler-5.5.12.jar:/opt/hbase-0.20.5/bin/../lib/jasper-runtime-5.5.12.jar:/opt/hbase-0.20.5/bin/../lib/jetty-6.1.14.jar:/opt/hbase-0.20.5/bin/../lib/jetty-util-6.1.14.jar:/opt/hbase-0.20.5/bin/../lib/jruby-complete-1.2.0.jar:/opt/hbase-0.20.5/bin/../lib/junit-3.8.1.jar:/opt/hbase-0.20.5/bin/../lib/libthrift-r771587.jar:/opt/hbase-0.20.5/bin/../lib/log4j-1.2.15.jar:/opt/hbase-0.20.5/bin/../lib/lucene-core-2.2.0.jar:/opt/hbase-0.20.5/bin/../lib/servlet-api-2.5-6.1.14.jar:/opt/hbase-0.20.5/bin/../lib/xmlenc-0.52.jar:/opt/hbase-0.20.5/bin/../lib/zookeeper-3.2.2.jar:/opt/hbase-0.20.5/bin/../lib/jsp-2.1/jsp-2.1.jar:/opt/hbase-0.20.5/bin/../lib/jsp-2.1/jsp-api-2.1.jar
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:java.library.path=/opt/hbase-0.20.5/bin/../lib/native/Linux-i386-32
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:os.name=Linux
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:os.arch=i386
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:os.version=2.6.18-164.el5
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:user.name=root
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:user.home=/root
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Client environment:user.dir=/opt/hbase-0.20.5/bin
10/07/07 11:06:16 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=60000 watcher=org.apache.hadoop.hbase.client.HConnectionManager$ClientZKWatcher@193722c
10/07/07 11:06:16 INFO zookeeper.ClientCnxn: zookeeper.disableAutoWatchReset is false
10/07/07 11:06:16 INFO zookeeper.ClientCnxn: Attempting connection to server localhost/127.0.0.1:2181
10/07/07 11:06:16 INFO zookeeper.ClientCnxn: Priming connection to java.nio.channels.SocketChannel[connected local=/127.0.0.1:43332 remote=localhost/127.0.0.1:2181]
10/07/07 11:06:16 INFO zookeeper.ClientCnxn: Server connection successful
10/07/07 11:06:16 DEBUG zookeeper.ZooKeeperWrapper: Read ZNode /hbase/master got 127.0.0.1:60000

And it does not return to shell. It stucks on that screen.

If I do a CRTL + C, thrift server stops and zohmg returns to the error above.

Now, if I run zohmg setup while thrift is up (and screen locked like above), zohmg returns me this:

creating table 'television'
Traceback (most recent call last):
  File "/usr/local/bin/zohmg", line 8, in <module>
    load_entry_point('zohmg==0.2.1', 'console_scripts', 'zohmg')()
  File "/usr/local/lib/python2.5/cmd.py", line 68, in zohmg
    identchars = IDENTCHARS
  File "/usr/local/lib/python2.5/cmd.py", line 90, in setup
    import sys
  File "build/bdist.linux-x86_64/egg/zohmg/setup.py", line 36, in go
  File "build/bdist.linux-x86_64/egg/zohmg/utils.py", line 50, in create_or_bust
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 835, in createTable
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 843, in send_createTable
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/Hbase.py", line 3500, in write
  File "/usr/local/lib/zohmg/egg/hbase-0.20-py2.5.egg/hbase/ttypes.py", line 206, in write
  File "/usr/local/lib/zohmg/egg/Thrift-0.1-py2.5-linux-i686.egg/thrift/protocol/TBinaryProtocol.py", line 123, in writeString
  File "/usr/local/lib/zohmg/egg/Thrift-0.1-py2.5-linux-i686.egg/thrift/transport/TTransport.py", line 159, in write
TypeError: write() argument 1 must be string or read-only character buffer, not dict

That is, the original error.

Now I am lost. Could thrift be the problem, ergo, hbase again ?

What do you think ?

**Comment by osimar** [comment]
This my current jps, at the time of the previous informed error:

[root@virid-tasks conf]# jps
21926 QuorumPeerMain
19758 SecondaryNameNode
21786 QuorumPeerMain
20528 Main
19839 JobTracker
22150 Jps
19959 TaskTracker
20243 HMaster
19644 DataNode
22037 Main
21369 ThriftServer

**Comment by osimar** [comment]
I've got an idea.

Can you give me the television hbase's table structure, so I can bypass the zohmg setup process ?

Can you do that ?

**Comment by fredrik** [comment]
Osimar, you can create the television table by hand in the hbase shell like so:
hbase(main):001:0> create 'television', {NAME => 'unit'}

**Comment by osimar** [comment]
That went well.

Thanks, bro.

About the previous errors, could you reproduce them ?

**Comment by fredrik** [comment]
Closing this as part of the Zohmg ceremonial service.
